blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/BotCoder254/piku/discussions
    about: For usage questions and open-ended discussion, please start a discussion instead of an issue.
